/*
 * generated by Xtext
 */
package com.netxforge.netxtest;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DragonXRuntimeModule extends com.netxforge.netxtest.AbstractDragonXRuntimeModule {

}
