/*
* generated by Xtext
*/
package com.netxforge.netxtest;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DragonXStandaloneSetup extends DragonXStandaloneSetupGenerated{

	public static void doSetup() {
		new DragonXStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

