/*
* generated by Xtext
*/
package com.netxforge.netxtest.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.netxforge.netxtest.services.DragonXGrammarAccess;

public class DragonXParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DragonXGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.netxforge.netxtest.parser.antlr.internal.InternalDragonXParser createParser(XtextTokenStream stream) {
		return new com.netxforge.netxtest.parser.antlr.internal.InternalDragonXParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "DragonX";
	}
	
	public DragonXGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DragonXGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
