/*
* generated by Xtext
*/
package com.netxforge.netxtest;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DragonXUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.netxforge.netxtest.ui.internal.DragonXActivator.getInstance().getInjector("com.netxforge.netxtest.DragonX");
	}
	
}
