/*
 * generated by Xtext
 */
package com.netxforge.netxtest.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.netxforge.netxtest.ui.internal.DragonXActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DragonXExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DragonXActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DragonXActivator.getInstance().getInjector(DragonXActivator.COM_NETXFORGE_NETXTEST_DRAGONX);
	}
	
}
