/*
 * generated by Xtext
 */
package com.netxforge.netxtest.ui.contentassist

import com.netxforge.netxtest.ui.contentassist.AbstractDragonXProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class DragonXProposalProvider extends AbstractDragonXProposalProvider {
}
