/*
 * generated by Xtext
 */
package com.netxforge.netxtest.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractDragonXValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.netxforge.netxtest.dragonX.DragonXPackage.eINSTANCE);
		return result;
	}
}
